- hosts: all
  become: yes
  become_method: sudo
  vars:
    install_cowsay: True
    swap: True
    swap_file_path: /swap
    swap_file_size: 2GB
  tasks:
    - name: ensure extra packages are available
      yum:
        name: epel-release
        state: present

    - name: ensure cowsay is installed
      yum:
        name: cowsay
        state: present
        # Add conditional logic so this only runs when the install_cowsay var is true
 
    - include: swap.yml
      # Even includes can have conditionals applied to them! Try making this execute only when swap is true



